name: Java CI with Maven and JaCoCo

on:
 push:
    branches:
      - long
  pull_request:
    branches:
      - long
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Đổi JDK phiên bản thành 17
        distribution: 'adoptopenjdk'  # Hoặc 'zulu' nếu bạn muốn sử dụng Zulu JDK

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with coverage
      run: mvn test
