name: Java CI with Maven and JaCoCo

on:
  push:
    branches:
      - long

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'zulu'
        
    - name: Install dependencies
      run: mvn clean install

    - name: Run tests with Maven
      run: mvn test  # Chỉ chạy lệnh test, không build lại dự án
