name: Java CI with Maven and JaCoCo

on:
  push:
    branches:
      - long

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Run tests with Maven
      run: mvn test  # Chỉ chạy lệnh test, không build lại dự án
